#!/bin/sh

set -e

set -u
ckbi=/usr/lib/firefox-esr/libnssckbi.so
if [ -z "$(dpkg-divert --listpackage $ckbi)" ]; then
    dpkg-divert --package calibre-browser-config \
            --rename --divert $ckbi.firefox-esr \
            --add $ckbi
    ln -sf ../x86_64-linux-gnu/pkcs11/p11-kit-trust.so $ckbi
fi
unset ckbi
set +u

set -u
ckbi=/usr/lib/iceweasel/libnssckbi.so
if [ calibre-browser-config = "$(dpkg-divert --listpackage $ckbi)" ]; then
    unlink $ckbi
    dpkg-divert --package calibre-browser-config \
            --rename --remove $ckbi
fi
unset ckbi
set +u

#DEBHELPER#

exit 0
